### PR TITLE
add tests and add permissions checks to op_open

### PR DESCRIPTION
**Pull request by fewf**

### CODE REVIEW

**Comment by dsseng** [comment]
Thanks, will check out

**Review by dsseng — COMMENTED** [review]
Good, but you need to format code and fix errors. @fewf thanks

**Comment by fewf** [comment]
Thanks for checking it out @sh7dm ! I formatted the code. What errors need to be fixed? Thanks for the help, this is my first contribution.

**Comment by dsseng** [comment]
@fewf 
```
************* Module fmt_test
C: 21, 0: Line too long (87/80) (line-too-long)
```
just wrap it and check with `python2 tools/lint.py`

**Comment by fewf** [comment]
awesome--done @sh7dm

**Review by dsseng — APPROVED** [review]
Tests passed, merging

**Comment by dsseng** [comment]
@fewf thanks a lot!

**Pull request merged**
